=== Jesse-perpC/mindquarry/trunk/mindquarry-persistence/trunk/xmlbeans-persistence-config/src/main/xsd/xmlbeans-persistence.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.mindquarry.com/ns/schema/xmlbeans-persistence"
	xmlns:tn="http://www.mindquarry.com/ns/schema/xmlbeans-persistence"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	attributeFormDefault="qualified" elementFormDefault="qualified">

	<xs:element name="configuration" type="tn:Configuration" />

	<xs:complexType name="Configuration">
		<xs:sequence>
			<xs:element name="entity" type="tn:Entity" maxOccurs="unbounded" />
			<xs:element name="queryInfo" type="tn:QueryInfo" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Entity">
		<xs:sequence>
			<xs:element name="className" type="xs:string" />
			<xs:element name="path" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="QueryInfo">
		<xs:sequence>
			<xs:element name="key" type="xs:string" />
			<xs:element name="query" type="xs:string" />
			<xs:element name="resultEntityClass" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Jesse-perpC/mindquarry/trunk/mindquarry-persistence/trunk/persistence-mock/src/test/resources/com/mindquarry/persistence/mock/mindquarry-persistence.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
	Copyright (C) 2006-2007 Mindquarry GmbH, All Rights Reserved
	
	The contents of this file are subject to the Mozilla Public License
	Version 1.1 (the "License"); you may not use this file except in
	compliance with the License. You may obtain a copy of the License at
	http://www.mozilla.org/MPL/
	
	Software distributed under the License is distributed on an "AS IS"
	basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
	License for the specific language governing rights and limitations
	under the License.
-->
<configuration
	xmlns="http://www.mindquarry.com/ns/schema/xmlbeans-persistence"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mindquarry.com/ns/schema/xmlbeans-persistence ../../../../../../main/xsd/xmlbeans-persistence.xsd ">
	<entity>
		<className>com.mindquarry.persistence.mock.UserEntity</className>
		<path>not necessary in mock implementation</path>
	</entity>
	<entity>
		<className>com.mindquarry.persistence.mock.TeamspaceEntity</className>
		<path>not necessary in mock implementation</path>
	</entity>
	<queryInfo>
		<key>getUserById</key>
		<query>byId</query>
		<resultEntityClass>com.mindquarry.persistence.mock.UserEntity</resultEntityClass>
	</queryInfo>
	<queryInfo>
		<key>getAllUsers</key>
		<query>byClass</query>
		<resultEntityClass>com.mindquarry.persistence.mock.UserEntity</resultEntityClass>
	</queryInfo>
	<queryInfo>
		<key>getTeamspaceById</key>
		<query>/teamspaces/{$id}/metadata.xml</query>
		<resultEntityClass>com.mindquarry.persistence.mock.TeamspaceEntity</resultEntityClass>
	</queryInfo>
	<queryInfo>
		<key>getAllTeamspaces</key>
		<query>/teamspaces</query>
		<resultEntityClass>com.mindquarry.persistence.mock.TeamspaceEntity</resultEntityClass>
	</queryInfo>
</configuration>

=== Jesse-perpC/mindquarry/mindquarry-persistence/trunk/xmlbeans-persistence/src/test/resources/com/mindquarry/persistence/xmlbeans/mindquarry-persistence.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration
	xmlns="http://www.mindquarry.com/ns/schema/xmlbeans-persistence"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.mindquarry.com/ns/schema/xmlbeans-persistence ../../../../../../main/xsd/xmlbeans-persistence.xsd ">
	<entity>
		<className>com.mindquarry.types.user.User</className>
		<path>/users</path>
	</entity>
	<entity>
		<className>com.mindquarry.types.teamspace.Teamspace</className>
		<path>/teamspaces</path>
	</entity>
	<queryInfo>
		<key>getUserById</key>
		<query>/users/{$userId}</query>
		<resultEntityClass>com.mindquarry.types.user.User</resultEntityClass>
	</queryInfo>
	<queryInfo>
		<key>getAllUsers</key>
		<query>/users</query>
		<resultEntityClass>com.mindquarry.types.user.User</resultEntityClass>
	</queryInfo>
</configuration>
